In [1]:
import numpy as np
import pandas as pd
import sklearn.preprocessing 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [2]:
data=pd.read_csv('data.csv')

In [3]:
df=data.copy()

In [4]:
df.head()

Mean RR*  STD RR (SDNN)  Mean HR*  Min HR    RMSSD  NNxx     pNNxx  \
0    711.63         37.729    84.314  68.650  26.4880   166  9.464100   
1    777.13         12.742    77.207  65.502   8.7235     1  0.062267   
2    620.35         21.315    96.720  80.000  17.4290    30  1.684400   
3    792.12         36.751    75.746  56.604  23.6630   113  7.266900   
4    672.65         39.062    89.199  71.090  21.7000   100  5.546300   

   HRV triangular index  TINN  Poincare plot, SD1  Poincare plot, SD2  \
0               12.8100   187              9.0405              28.248   
1                4.3668    70              6.1704              16.934   
2                5.3036   194              7.9726              20.423   
3               11.7880   200             16.7380              49.142   
4               10.8670   239             15.3490              53.069   

   FFT Power (ms2)  FFT Power (log)  AR Power (ms2)  AR Power (log)  \
0           268.18           5.5917          289.26          5.6673   
1           101.23           4.6174          101.64          4.6215   
2           169.02           5.1300          181.95          5.2037   
3           900.60           6.8031          862.01          6.7593   
4          1115.30           7.0169         1111.80          7.0137   

   FFT Power (ms2).1  FFT Power (log).1  AR Power (ms2).1  AR Power (log).1  \
0             53.782             3.9849            56.074            4.0267   
1             23.747             3.1674            22.940            3.1329   
2            114.770             4.7429           167.440            5.1206   
3            157.190             5.0574           156.600            5.0537   
4            130.210             4.8692           134.590            4.9023   

   Class  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
df['Class'].value_counts()

1    31
0    31
Name: Class, dtype: int64

In [6]:
df.isnull().sum()

Mean RR*                0
STD RR (SDNN)           0
Mean HR*                0
Min HR                  0
RMSSD                   0
NNxx                    0
pNNxx                   0
HRV triangular index    0
TINN                    0
Poincare plot, SD1      0
Poincare plot, SD2      0
FFT Power (ms2)         0
FFT Power (log)         0
AR Power (ms2)          0
AR Power (log)          0
FFT Power (ms2).1       0
FFT Power (log).1       0
AR Power (ms2).1        0
AR Power (log).1        0
Class                   0
dtype: int64

In [7]:
X = df.drop(['Class'], axis=1)
Y = df[['Class']]
print(X.shape)
print(Y.shape)

(62, 19)
(62, 1)


In [8]:
from sklearn.model_selection import train_test_split

In [117]:
xtrain, xtest, ytrain, ytest =  train_test_split(X, Y, test_size=0.30,random_state=25, shuffle=True)
print(xtrain.shape, ytrain.shape)
print(xtest.shape, ytest.shape)

(43, 19) (43, 1)
(19, 19) (19, 1)


In [118]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X_ = scaler.transform(X)
X = pd.DataFrame(data=X_, columns = X.columns)
X.head()

Mean RR*  STD RR (SDNN)  Mean HR*    Min HR     RMSSD      NNxx     pNNxx  \
0  0.401256       0.653810  0.470787  0.416693  0.737792  1.000000  0.918450   
1  0.574075       0.029603  0.306660  0.340000  0.091925  0.000000  0.001211   
2  0.160418       0.243767  0.757286  0.693205  0.408433  0.175758  0.159466   
3  0.613625       0.629378  0.272920  0.123225  0.635083  0.678788  0.704092   
4  0.298409       0.687110  0.583599  0.476137  0.563714  0.600000  0.536231   

   HRV triangular index      TINN  Poincare plot, SD1  Poincare plot, SD2  \
0              0.807649  0.517699            0.239429            0.238950   
1              0.106113  0.000000            0.091920            0.029719   
2              0.183951  0.548673            0.184544            0.094241   
3              0.722732  0.575221            0.635043            0.625347   
4              0.646207  0.747788            0.563655            0.697969   

   FFT Power (ms2)  FFT Power (log)  AR Power (ms2)  AR Power (log)  \
0         0.132235         0.500822        0.165557        0.512768   
1         0.035240         0.242456        0.034835        0.201518   
2         0.074625         0.378388        0.090790        0.374792   
3         0.499659         0.822063        0.564615        0.837768   
4         0.624396         0.878759        0.738653        0.913482   

   FFT Power (ms2).1  FFT Power (log).1  AR Power (ms2).1  AR Power (log).1  
0           0.127212           0.496554          0.131694          0.464713  
1           0.043601           0.282342          0.033964          0.203628  
2           0.296988           0.695176          0.460174          0.784250  
3           0.415075           0.777586          0.428201          0.764708  
4           0.339969           0.728271          0.363281          0.720483

In [119]:
xtrain.head()

Mean RR*  STD RR (SDNN)  Mean HR*    Min HR     RMSSD      NNxx     pNNxx  \
60  0.361705       0.296852  0.512655  0.484396  0.254606  0.115152  0.107340   
43  0.733384       0.620010  0.178121  0.095184  0.578075  0.454545  0.503324   
6   0.588296       0.554209  0.294374  0.235778  0.546844  0.363636  0.367785   
37  0.401968       0.308369  0.470048  0.205959  0.348407  0.260606  0.239728   
11  0.710694       0.751187  0.195280  0.180111  0.729721  0.769697  0.855163   

    HRV triangular index      TINN  Poincare plot, SD1  Poincare plot, SD2  \
60              0.403438  0.309735            0.239167            0.303639   
43              0.515957  0.818584            0.578046            0.622961   
6               0.318064  0.743363            0.546798            0.554407   
37              0.380414  0.256637            0.348361            0.306376   
11              0.811637  0.606195            0.729662            0.749399   

    FFT Power (ms2)  FFT Power (log)  AR Power (ms2)  AR Power (log)  \
60         0.170922         0.559613        0.201293        0.561369   
43         0.308615         0.701565        0.487876        0.797083   
6          0.328287         0.716839        0.395181        0.739107   
37         0.158274         0.541793        0.195447        0.553929   
11         0.698587         0.907505        0.651205        0.877827   

    FFT Power (ms2).1  FFT Power (log).1  AR Power (ms2).1  AR Power (log).1  
60           0.145348           0.526531          0.139310          0.477858  
43           0.373486           0.751435          0.375404          0.729246  
6            0.442022           0.793255          0.406905          0.750920  
37           0.228190           0.631633          0.207333          0.574721  
11           0.628729           0.881797          0.544236          0.830169

In [120]:
ytrain.head()

Class
60      1
43      1
6       0
37      1
11      0

In [121]:
from sklearn.linear_model import LogisticRegression

In [122]:
lr_model = LogisticRegression(random_state=25)

In [123]:
lr_model.fit(xtrain, ytrain)

C:\Users\furqa\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\furqa\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=25, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [124]:
pred = lr_model.predict(xtest)

In [125]:
from sklearn.metrics import accuracy_score
accuracy_lr = accuracy_score(ytest, pred)
accuracy_lr

0.631578947368421

In [127]:
from sklearn.model_selection import cross_val_score

In [154]:
scores = cross_val_score(lr_model, xtrain, ytrain, cv=5)

C:\Users\furqa\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\furqa\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\furqa\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\furqa\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using rave

In [155]:
scores

array([0.33333333, 0.66666667, 0.77777778, 0.5       , 0.75      ])

In [156]:
scores.mean()

0.6055555555555555

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
confusion_matrix(ytest, pred)

array([[7, 1],
       [5, 6]], dtype=int64)

In [21]:
confusion_matrix(ytest, pred).ravel()

array([7, 1, 5, 6], dtype=int64)

In [22]:
tn, fp, fn, tp = confusion_matrix(ytest, pred).ravel()
conf_matrix=pd.DataFrame({"pred_have stress":[tp,fp],"pred_Not stress":[fn,tn]},index=[" have stress","Not Stress"])
conf_matrix

pred_have stress  pred_Not stress
 have stress                 6                5
Not Stress                   1                7

In [23]:
from sklearn.metrics import precision_score

In [152]:
accuracy = (tp + tn) / (tp + fp + tn + fn)
print("Accuracy: {}".format(accuracy))

Accuracy: 0.6842105263157895


In [153]:
accuracy_lr = accuracy_score(ytest,pred)
print("Accuracy by built-in function: {}".format(accuracy_lr))

Accuracy by built-in function: 0.631578947368421
